open_data/app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('scores/', views.scores_page, name='scores'),
]

open_data/badge/urls.py
from django.urls import path

from .views import badge_list

app_name = "pinax_badges"

urlpatterns = [
    path("<str:username>/", badge_list, name="badge_list"),
]

open_data/open_data/urls.py
import notifications.urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('', include('app.urls')),
    path('user/', include('user.urls')),
    path('data/', include('dataset.urls')),
    path('quiz/', include('quiz.urls')),
    path('badges/', include('badge.urls', namespace="badges")),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('admin/', admin.site.urls),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

open_data/badge/models.py
from django.db import models
from django.utils import timezone

from user.models import User


class BadgeAward(models.Model):
    user = models.ForeignKey(User, related_name="badges_earned", on_delete=models.CASCADE)
    awarded_at = models.DateTimeField(default=timezone.now)
    slug = models.CharField(max_length=255)
    level = models.IntegerField()

    def __getattr__(self, attr):
        return getattr(self._badge, attr)

    def __str__(self):
        return f"{self.name!r} ({self.user.profile.name})"

    @property
    def _badge(self):
        from badge.registry import BadgeCache
        return BadgeCache.instance().get_badge(self.slug)

    @property
    def name(self):
        return self._badge.levels[self.level].name

    @property
    def description(self):
        return self._badge.levels[self.level].description

    @property
    def image(self):
        return self._badge.levels[self.level].image

    @property
    def progress(self):
        return self._badge.progress(self.user, self.level)

    @property
    def x(self):
        return self._badge.positions[self.level][0]
    
    @property
    def y(self):
        return self._badge.positions[self.level][1]

    @property
    def score(self):
        return self._badge.levels[self.level].score

open_data/badge/views.py
from django.shortcuts import render, get_object_or_404

from badge.models import BadgeAward
from badge.registry import BadgeCache
from .models import User


def badge_list(request, username):
    user = get_object_or_404(User, username=username)
    cache = BadgeCache.instance()

    # Make a list of every available badge
    badges = {}
    for badge in cache.badges:
        for level in range(len(badge.levels)):
            name = f'{badge.slug}:{level}'
            badges[name] = {
                'slug': badge.slug,
                'level': level,
                'name': badge.levels[level].name,
                'description': badge.levels[level].description,
                'image': badge.levels[level].image,
                'score': badge.levels[level].score,
                'x': badge.positions[level][0],
                'y': badge.positions[level][1],
                'visible': False,
                'earned': False,
            }

    # Annotate earned badges
    visible_positions = set()
    if user.is_authenticated:
        for badge_obj in user.badges_earned.all():
            name = f'{badge_obj.slug}:{badge_obj.level}'
            badge = badges[name]

            badge['earned'] = True

            x, y = badge['x'], badge['y']
            visible_positions.add((x, y))
            visible_positions.add((x, y - 1))
            visible_positions.add((x + 1, y))
            visible_positions.add((x, y + 1))
            visible_positions.add((x - 1, y))

    # Annotate visible badges
    for badge in badges.values():
        if (badge['x'], badge['y']) in visible_positions:
            badge['visible'] = True

    return render(request, 'badges.html', {'badges': badges, "profile": user.profile})


def badge_detail(request, slug, level):
    badge = BadgeCache.instance().get_badge(slug).levels[int(level)]
    badge_awards = BadgeAward.objects.filter(
        slug=slug,
        level=level
    ).order_by("-awarded_at")

    badge_count = badge_awards.count()
    latest_awards = badge_awards[:50]

    return render(request, "badge_detail.html", {
        "badge": badge,
        "badge_count": badge_count,
        "latest_awards": latest_awards,
    })

open_data/badge/templates/badge_detail.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<img class="badge" src="{{ STATIC_PREFIX }}images/badges/{{ badge.image }}" alt=""/>
{{ badge.name }}

<style>
    .badge {
        width: 64px;
        height: 64px;
    }
</style>

open_data/badge/templates/badges.html
{% extends 'base.html' %}
{% load static pinax_badges_tags %}

{% block title %}Mes badges{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/badges.css' %}">
{% endblock %}

{% block main %}
  <div class="breadcrumbs">
    <a href="{% url 'home' %}">Accueil <i class="fas fa-home"></i></a>
    <a href="{% url 'pinax_badges:badge_list' profile.user.username %}">
      {% if profile == user.profile %}Mes badges{% else %}Les badges de
        {{ profile.name }}{% endif %}
      <i class="fas fa-medal"></i>
    </a>
  </div>
  <h1>
    {% if profile == user.profile %}
      Mes badges
    {% else %}
      Les badges de <a href="{% url "profile" username=profile.user.username %}">{{ profile.name }}</a>
    {% endif %}
  </h1>
  <div class="badges">
    {% for badge in badges.values %}
      <div
              class="{% if not badge.visible %}locked {% elif not badge.earned %}visible {% endif %}badge badge{{ forloop.counter }}-tab-button"
              style="grid-area: {{ badge.y }} / {{ badge.x }};"
              data-tooltip="{% if badge.visible %}{{ badge.name }}{% else %}?{% endif %}"
      >
        <img src="{{ badge.image }}" alt="Badge">
      </div>
    {% endfor %}
  </div>
  <div class="tabs">
    {% for badge in badges.values %}
      <div id="badge{{ forloop.counter }}-tab" class="card tab">
        {% if badge.earned or badge.visible %}
          <p>
            <b>{{ badge.name }}</b>
            <span>({{ badge.score }} points)</span>
          </p>
          <p>
            <i>{{ badge.description }}</i>
          </p>
        {% else %}
          <p><b>?</b></p>
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% endblock %}